
name: 'marketo_source'
version: '1.0.0'

require-dbt-version: '>=0.17.0'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
    marketo_source:
        lead: "{{ source('marketo','lead') }}"
        lead_describe: "{{ source('marketo','lead_describe') }}"
        campaign: "{{ source('marketo','campaign') }}"
        email_template_history: "{{ source('marketo','email_template_history') }}"
        activity_change_data_value: "{{ source('marketo','activity_change_data_value') }}"
        activity_click_email: "{{ source('marketo','activity_click_email') }}"
        activity_click_link: "{{ source('marketo','activity_click_link') }}"
        activity_email_delivered: "{{ source('marketo','activity_email_delivered') }}"
        activity_email_bounced: "{{ source('marketo','activity_email_bounced') }}"
        activity_open_email: "{{ source('marketo','activity_open_email') }}"
        activity_unsubscribe_email: "{{ source('marketo','activity_unsubscribe_email') }}"
        activity_send_email: "{{ source('marketo','activity_send_email') }}"
        schema: marketo
        database: raw
